// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://kuyjsfpzfysiwczrzefx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1eWpzZnB6ZnlzaXdjenJ6ZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA5MjIwNjgsImV4cCI6MjA0NjQ5ODA2OH0.XQp1Kuw4NxCDeSp3p_LeZHNrZvxw3RBHB3O4HFMGBLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);